#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Aug 30 16:18:55 2017

@author: eder
"""
"""
u=[1,4.,'a']
v=[3.2,'x',u]
w=v+u
w.append('xy')
s=u # faz referência a u
print(s)
print(u)
s[1]=3
print(s)
print(u)
u=[1,4.,'a']
s=u[:] # faz uma cópia de u
print(s)
print(u)
s[1]=3
print(s)
print(u)
import numpy as np
a=np.array([[1,2],[1,2]],dtype=int)
b=np.zeros((2,2),dtype=int)
c=np.ones((2,2),dtype=int)
d=b+c
import numpy as np
A=np.array([[1,2,3],[4,3,2],[2,2,1]])
b=np.array([1,1,2])
x=np.linalg.solve(A,b)
resid=np.dot(A,x)-b
import numpy as np
a=np.array([1,2,3])
b=np.array([3,2,1])
c=np.vstack((a,b))
d=np.hstack((a,b))


for i in range(1,4):
    print(i)
"""